monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - login
        - password
    handlers:
        console:
            type: console
            process_psr_3_messages: false
            channels: [ '!event', '!doctrine' ]
        rotating_file_login:
            type: rotating_file
            path: '%kernel.logs_dir%/login/login_attempts.log'
            level: info
            channels: [ 'login' ]
            max_files: 30
            date_format: 'Y-m'
        rotating_file_password_request:
            type: rotating_file
            path: '%kernel.logs_dir%/password_request/password_request_attempts.log'
            level: info
            channels: [ 'password' ]
            max_files: 30
            date_format: 'Y-m'

when@dev:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: grouped
                excluded_http_codes: [ 403, 404, 405 ]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            grouped:
                type: group
                members:
                    - rotated
            rotated:
                type: rotating_file
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: error
                max_files: 30
                date_format: 'Y-m'
                channels: [ '!event' ]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: grouped
                excluded_http_codes: [403, 404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            grouped:
                type: group
                members:
                    - rotated
                    - deduplicated
            rotated:
                type: rotating_file
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: error
                max_files: 30
                date_format: 'Y-m'
                channels: ['!event']
            deduplicated:
                type: deduplication
                handler: mailed
            mailed:
                type: symfony_mailer
                from_email: '%contact_email%'
                to_email: '%developer_email%'
                level: error
                subject: Erreur critique
                formatter: monolog.formatter.html
                content_type: text/html
