twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        'assets/images': images
    form_themes:
        # Add here form themes
    globals:
        contact_email: '%contact_email%'
        site_name: '%site_name%'

when@test:
    twig:
        strict_variables: true