api_platform:
  show_webby: false
  graphql:
    graphiql:
      enabled: false
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  formats:
    jsonld:
      mime_types:
        - application/ld+json
    json:
      mime_types:
        - application/json
    html:
      mime_types:
        - text/html
  patch_formats:
    json:
      mime_types:
        - application/merge-patch+json
  swagger:
    versions:
      - 3