vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        user_picture_file:
            uri_prefix: /uploads/pictures/users
            upload_destination: '%upload_directory%/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
