INSERT INTO `unit` (`id`, `label`, `abbreviation`, `created_at`, `updated_at`, `pluralizable`) VALUES
(1, 'Milligramme', 'mg', NOW(), NOW(), 0),
(2, 'Centigramme', 'cg', NOW(), NOW(), 0),
(3, 'Décigramme', 'dg', NOW(), NOW(), 0),
(4, 'Gramme', 'g', NOW(), NOW(), 0),
(5, 'Kilogramme', 'kg', NOW(), NOW(), 0),
(6, 'Millilitre', 'ml', NOW(), NOW(), 0),
(7, 'Centilitre', 'cl', NOW(), NOW(), 0),
(8, 'DéciLitre', 'dl', NOW(), NOW(), 0),
(9, 'Litre', 'l', NOW(), NOW(), 0),
(10, 'Cuillère à soupe', 'c. à s.', NOW(), NOW(), 0),
(11, 'Cuillère à café', 'c. à c.', NOW(), NOW(), 0),
(12, 'Once', 'oz', NOW(), NOW(), 0),
(13, 'Livre', 'lb', NOW(), NOW(), 0),
(14, 'Pinte', 'pt', NOW(), NOW(), 0),
(15, 'Quart de gallon', 'qt', NOW(), NOW(), 0),
(16, 'Gallon', 'gal', NOW(), NOW(), 0),
(17, 'Tasse', 'tasse', NOW(), NOW(), 1),
(18, 'Pouce', 'po', NOW(), NOW(), 0),
(19, 'Millimètre', 'mm', NOW(), NOW(), 0),
(20, 'Centimètre', 'cm', NOW(), NOW(), 0),
(21, 'Décimètre', 'dm', NOW(), NOW(), 0),
(22, 'Mètre', 'm', NOW(), NOW(), 0),
(23, 'Cup', 'cup', NOW(), NOW(), 1),
(24, 'Demi-tasse', '1/2 tasse', NOW(), NOW(), 1),
(25, 'Quart de tasse', '1/4 tasse', NOW(), NOW(), 1),
(26, 'Verre', 'verre', NOW(), NOW(), 1),
(27, 'Petit verre', 'p. verre', NOW(), NOW(), 1),
(28, 'Grand verre', 'g. verre', NOW(), NOW(), 1),
(29, 'Once liquide', 'fl oz', NOW(), NOW(), 0),
(30, 'Livre anglaise', 'lbs', NOW(), NOW(), 0),
(31, 'Pincée', 'pincée', NOW(), NOW(), 1),
(32, 'Poignée', 'poignée', NOW(), NOW(), 1),
(33, 'Goutte', 'gte', NOW(), NOW(), 1),
(34, 'Trait', 'trait', NOW(), NOW(), 1),
(35, 'Dose', 'dose', NOW(), NOW(), 1),
(36, 'Tranche', 'tr.', NOW(), NOW(), 0),
(37, 'Lamelle', 'lam.', NOW(), NOW(), 0),
(38, 'Rondelle', 'rond.', NOW(), NOW(), 0),
(39, 'Morceau', 'morc.', NOW(), NOW(), 0),
(40, 'Petit morceau', 'p. morc.', NOW(), NOW(), 0),
(41, 'Grand morceau', 'g. morc.', NOW(), NOW(), 0),
(42, 'Barquette', 'barq.', NOW(), NOW(), 0),
(43, 'Boîte', 'bte', NOW(), NOW(), 1),
(44, 'Conserve', 'cons.', NOW(), NOW(), 0),
(45, 'Brique', 'briq.', NOW(), NOW(), 0),
(46, 'Sachet', 'sachet', NOW(), NOW(), 1),
(47, 'Paquet', 'pqt', NOW(), NOW(), 1),
(48, 'Tablette', 'tablette', NOW(), NOW(), 1),
(49, 'Plaque', 'plq', NOW(), NOW(), 0),
(50, 'Ramequin', 'ram.', NOW(), NOW(), 0),
(51, 'Moule', 'mle', NOW(), NOW(), 0),
(52, 'Bocal', 'boc.', NOW(), NOW(), 0),
(53, 'Pot', 'pot', NOW(), NOW(), 1),
(54, 'Bouteille', 'bouteille', NOW(), NOW(), 1),
(55, 'Quart', '1/4', NOW(), NOW(), 0),
(56, 'Demi', '1/2', NOW(), NOW(), 0),
(57, 'Trois quart', '3/4', NOW(), NOW(), 0),
(58, 'Douzaine', 'dz', NOW(), NOW(), 0),
(59, 'Demie douzaine', '1/2 dz', NOW(), NOW(), 0),
(60, 'Tour', 'tour', NOW(), NOW(), 1);