# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # https://symfony.com/doc/6.4/performance.html#dump-the-service-container-into-a-single-file
    .container.dumper.inline_factories: true
    contact_email: '%env(CONTACT_EMAIL)%'
    developer_email: '%env(CONTACT_EMAIL)%'
    site_name: '%env(SITE_NAME)%'
    site_url: '%env(SITE_URL)%'
    site_logo_path: '%env(SITE_LOGO_PATH)%'

imports:
    - { resource: '../vendor/ice/vich-uploader-bundle/Resources/config/config.yml' }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\UserActivationListener:
        arguments:
            $tokenStorage: '@security.token_storage'
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 0 }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    admin.user:
        class: App\Admin\UserAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\User, controller: App\Controller\Admin\UserAdminCRUDController,  manager_type: orm, label: common.users }

    admin.city:
        class: App\Admin\CityAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\City, manager_type: orm }

    admin.difficulty:
        class: App\Admin\DifficultyAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Difficulty,  manager_type: orm, label: common.difficulties }

    admin.cost:
        class: App\Admin\CostAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Cost,  manager_type: orm, label: common.costs }

    admin.cooking_type:
        class: App\Admin\CookingTypeAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\CookingType,  manager_type: orm, label: common.cooking_types }

    admin.unit:
        class: App\Admin\UnitAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Unit,  manager_type: orm, label: common.units }
