INSERT INTO `country` (`id`, `label`, `code`) VALUES
(1, 'Guernesey, île', 'GG'),
(2, 'Jersey, île', 'JE'),
(3, 'Canaries', 'IC'),
(4, 'Andorre', 'AD'),
(5, 'Emirats Arabes Unis', 'AE'),
(6, 'Afghanistan', 'AF'),
(7, 'Antigua-et-Barbuda', 'AG'),
(8, 'Anguilla', 'AI'),
(9, 'Albanie', 'AL'),
(10, 'Arménie', 'AM'),
(11, 'Antilles néerlandaises', 'AN'),
(12, 'Angola', 'AO'),
(13, 'Antarctique', 'AQ'),
(14, 'Argentine', 'AR'),
(15, 'Samoa américaines', 'AS'),
(16, 'Autriche', 'AT'),
(17, 'Australie', 'AU'),
(18, 'Aruba', 'AW'),
(19, 'Azerbaïdjan', 'AZ'),
(20, 'Bosnie-Herzégovine', 'BA'),
(21, 'Barbade', 'BB'),
(22, 'Bangladesh', 'BD'),
(23, 'Belgique', 'BE'),
(24, 'Burkina Fasso', 'BF'),
(25, 'Bulgarie', 'BG'),
(26, 'Bahreïn', 'BH'),
(27, 'Burundi', 'BI'),
(28, 'Bénin', 'BJ'),
(29, 'Bermudes', 'BM'),
(30, 'Brunéi Darussalam', 'BN'),
(31, 'Bolivie', 'BO'),
(32, 'Brésil', 'BR'),
(33, 'Bahamas', 'BS'),
(34, 'Bhoutan', 'BT'),
(35, 'Bouvet (île)', 'BV'),
(36, 'Botswana', 'BW'),
(37, 'Bélarus', 'BY'),
(38, 'Belize', 'BZ'),
(39, 'Canada', 'CA'),
(40, 'Cocos, îles', 'CC'),
(41, 'Congo, la république démocratique du', 'CD'),
(42, 'Centrafricaine, République', 'CF'),
(43, 'Congo', 'CG'),
(44, 'Suisse', 'CH'),
(45, 'Côte d''Ivoire', 'CI'),
(46, 'Cook, îles', 'CK'),
(47, 'Chili', 'CL'),
(48, 'Cameroun', 'CM'),
(49, 'Chine', 'CN'),
(50, 'Colombie', 'CO'),
(51, 'Costa Rica', 'CR'),
(52, 'Serbie-et-Monténégro', 'CS'),
(53, 'Cuba', 'CU'),
(54, 'Cap-Vert', 'CV'),
(55, 'Christmas, îles', 'CX'),
(56, 'Chypre', 'CY'),
(57, 'Rèpublique tchèque', 'CZ'),
(58, 'Allemagne', 'DE'),
(59, 'Djibouti', 'DJ'),
(60, 'Danemark', 'DK'),
(61, 'Dominique', 'DM'),
(62, 'Dominicaine, République', 'DO'),
(63, 'Dubaï', 'DU'),
(64, 'Algérie', 'DZ'),
(65, 'Equateur', 'EC'),
(66, 'Estonie', 'EE'),
(67, 'Egypte', 'EG'),
(68, 'Sahara occidental', 'EH'),
(69, 'Erythrée', 'ER'),
(70, 'Espagne', 'ES'),
(71, 'Ethiopie', 'ET'),
(72, 'Finlande', 'FI'),
(73, 'Fidji, îles', 'FJ'),
(74, 'Falkland, îles', 'FK'),
(75, 'Micronésie, Etats fédérés de', 'FM'),
(76, 'Féroé, îles', 'FO'),
(77, 'France', 'FR'),
(78, 'Gabon', 'GA'),
(79, 'Royaume-Uni', 'GB'),
(80, 'Grenade', 'GD'),
(81, 'Géorgie', 'GE'),
(82, 'Guyane française', 'GF'),
(83, 'Ghana', 'GH'),
(84, 'Gibraltar', 'GI'),
(85, 'Groenland', 'GL'),
(86, 'Gambie', 'GM'),
(87, 'Guinée', 'GN'),
(88, 'Guadeloupe', 'GP'),
(89, 'Guinée équatoriale', 'GQ'),
(90, 'Grèce', 'GR'),
(91, 'Géorgie du Sud et les îles Sandwich du sud', 'GS'),
(92, 'Guatemala', 'GT'),
(93, 'Guam', 'GU'),
(94, 'Guinée-Bissau', 'GW'),
(95, 'Guyane', 'GY'),
(96, 'Hong-Kong', 'HK'),
(97, 'Heard, îles et Mcdonald, îles', 'HM'),
(98, 'Honduras', 'HN'),
(99, 'Croatie', 'HR'),
(100, 'Haïti', 'HT'),
(101, 'Hongrie', 'HU'),
(102, 'Indonésie', 'ID'),
(103, 'Irlande', 'IE'),
(104, 'Israël', 'IL'),
(105, 'Inde', 'IN'),
(106, 'Océan indien, Territoire britannique de l''', 'IO'),
(107, 'Iraq', 'IQ'),
(108, 'Iran', 'IR'),
(109, 'Islande', 'IS'),
(110, 'Italie', 'IT'),
(111, 'Jamaïque', 'JM'),
(112, 'Jordanie', 'JO'),
(113, 'Japon', 'JP'),
(114, 'Kenya', 'KE'),
(115, 'Kirghizistan', 'KG'),
(116, 'Cambodge', 'KH'),
(117, 'Kiribati', 'KI'),
(118, 'Comores', 'KM'),
(119, 'Saint-Kitts-et-Nevis', 'KN'),
(120, 'Corée, République populaire démocratique de', 'KP'),
(121, 'Corée, République de', 'KR'),
(122, 'Koweït', 'KW'),
(123, 'Caïmanes, îles', 'KY'),
(124, 'Kazakhstan', 'KZ'),
(125, 'Laos, République démocratique populaire du', 'LA'),
(126, 'Liban', 'LB'),
(127, 'Sainte-Lucie', 'LC'),
(128, 'Liechtenstein', 'LI'),
(129, 'Sri Lanka', 'LK'),
(130, 'Libéria', 'LR'),
(131, 'Lesotho', 'LS'),
(132, 'Lituanie', 'LT'),
(133, 'Luxembourg', 'LU'),
(134, 'Lettonie', 'LV'),
(135, 'Libye', 'LY'),
(136, 'Maroc', 'MA'),
(137, 'Monaco', 'MC'),
(138, 'Moldova, République de', 'MD'),
(139, 'Madagascar', 'MG'),
(140, 'Macédoine', 'MK'),
(141, 'Mali', 'ML'),
(142, 'Birmanie (Myanmar)', 'MM'),
(143, 'Mongolie', 'MN'),
(144, 'Macao', 'MO'),
(145, 'Mariannes du Nord, îles', 'MP'),
(146, 'Martinique', 'MQ'),
(147, 'Mauritanie', 'MR'),
(148, 'Montserrat', 'MS'),
(149, 'Malte', 'MT'),
(150, 'Maurice, île', 'MU'),
(151, 'Maldives', 'MV'),
(152, 'Malawi', 'MW'),
(153, 'Mexique', 'MX'),
(154, 'Malaisie', 'MY'),
(155, 'Mozambique', 'MZ'),
(156, 'Namibie', 'NA'),
(157, 'Nouvelle-Calédonie', 'NC'),
(158, 'Niger', 'NE'),
(159, 'Norfolk, île', 'NF'),
(160, 'Nigéria', 'NG'),
(161, 'Nicaragua', 'NI'),
(162, 'Pays-Bas', 'NL'),
(163, 'Norvège', 'NO'),
(164, 'Népal', 'NP'),
(165, 'Nauru', 'NR'),
(166, 'Niué', 'NU'),
(167, 'Nouvelle-Zélande', 'NZ'),
(168, 'Oman', 'OM'),
(169, 'Panama', 'PA'),
(170, 'Pérou', 'PE'),
(171, 'Polynésie française', 'PF'),
(172, 'Papouasie Nouvelle Guinée', 'PG'),
(173, 'Philippines', 'PH'),
(174, 'Pakistan', 'PK'),
(175, 'Pologne', 'PL'),
(176, 'Saint-Pierre et Miquelon', 'PM'),
(177, 'Pitcairn', 'PN'),
(178, 'Porto Rico', 'PR'),
(179, 'Palestinien, Territoire', 'PS'),
(180, 'Portugal', 'PT'),
(181, 'Palaos', 'PW'),
(182, 'Paraguay', 'PY'),
(183, 'Qatar', 'QA'),
(184, 'Réunion', 'RE'),
(185, 'Roumanie', 'RO'),
(186, 'Russie', 'RU'),
(187, 'Rwanda', 'RW'),
(188, 'Arabie saoudite', 'SA'),
(189, 'Salomon, îles', 'SB'),
(190, 'Seychelles', 'SC'),
(191, 'Soudan', 'SD'),
(192, 'Suède', 'SE'),
(193, 'Singapour', 'SG'),
(194, 'Sainte-Hélène', 'SH'),
(195, 'Slovénie', 'SI'),
(196, 'Svalbard et île Jan Mayen', 'SJ'),
(197, 'Slovaquie', 'SK'),
(198, 'Sierra Leone', 'SL'),
(199, 'Saint-Marin', 'SM'),
(200, 'Sénégal', 'SN'),
(201, 'Somalie', 'SO'),
(202, 'Suriname', 'SR'),
(203, 'Sao Tomé-et-Principe', 'ST'),
(204, 'El Salvador', 'SV'),
(205, 'Syrie', 'SY'),
(206, 'Swaziland', 'SZ'),
(207, 'Turks et Caïques, îles', 'TC'),
(208, 'Tchad', 'TD'),
(209, 'Terres Australes françaises', 'TF'),
(210, 'Togo', 'TG'),
(211, 'Thaïlande', 'TH'),
(212, 'Tadjikistan', 'TJ'),
(213, 'Tokelau', 'TK'),
(214, 'Timor-Leste', 'TL'),
(215, 'Turkménistan', 'TM'),
(216, 'Tunisie', 'TN'),
(217, 'Tonga', 'TO'),
(218, 'Turquie', 'TR'),
(219, 'Trinité & Tobago', 'TT'),
(220, 'Taïwan', 'TW'),
(221, 'Tanzanie, République Unie de', 'TZ'),
(222, 'Ukraine', 'UA'),
(223, 'Ouganda', 'UG'),
(224, 'Iles mineures éloignées des Etats-Unis', 'UM'),
(225, 'Etats-Unis', 'US'),
(226, 'Uruguay', 'UY'),
(227, 'Ouzbékistan', 'UZ'),
(228, 'Saint-Siège (Vatican)', 'VA'),
(229, 'Saint-Vincent et les Grenadines', 'VC'),
(230, 'Venezuela', 'VE'),
(231, 'Iles vierges britanniques', 'VG'),
(232, 'Iles vierges des Etats-Unis', 'VI'),
(233, 'Vietnam', 'VN'),
(234, 'Vanuatu', 'VU'),
(235, 'Wallis et Futuna', 'WF'),
(236, 'Samoa', 'WS'),
(238, 'Yémen', 'YE'),
(239, 'Mayotte', 'YT'),
(240, 'Afrique du Sud', 'ZA'),
(241, 'Zambie', 'ZM'),
(242, 'Zimbabwe', 'ZW');