INSERT INTO `unit` (`id`, `label`, `abbreviation`, `created_at`, `updated_at`) VALUES
(1, 'Milligramme', 'mg', NOW(), NOW()),
(2, 'Centigramme', 'cg', NOW(), NOW()),
(3, 'Décigramme', 'dg', NOW(), NOW()),
(4, 'Gramme', 'g', NOW(), NOW()),
(5, 'Kilogramme', 'kg', NOW(), NOW()),
(6, 'Millilitre', 'ml', NOW(), NOW()),
(7, 'Centilitre', 'cl', NOW(), NOW()),
(8, 'DéciLitre', 'dl', NOW(), NOW()),
(9, 'Litre', 'l', NOW(), NOW()),
(10, 'Cuillère à soupe', 'c. à s.', NOW(), NOW()),
(11, 'Cuillère à café', 'c. à c.', NOW(), NOW()),
(12, 'Once', 'oz', NOW(), NOW()),
(13, 'Livre', 'lb', NOW(), NOW()),
(14, 'Pinte', 'pt', NOW(), NOW()),
(15, 'Quart de gallon', 'qt', NOW(), NOW()),
(16, 'Gallon', 'gal', NOW(), NOW()),
(17, 'Tasse', 'tasse', NOW(), NOW()),
(18, 'Pouce', 'po', NOW(), NOW()),
(19, 'Millimètre', 'mm', NOW(), NOW()),
(20, 'Centimètre', 'cm', NOW(), NOW()),
(21, 'Décimètre', 'dm', NOW(), NOW()),
(22, 'Mètre', 'm', NOW(), NOW()),
(23, 'Cup', 'cup', NOW(), NOW()),
(24, 'Demi-tasse', '1/2 tasse', NOW(), NOW()),
(25, 'Quart de tasse', '1/4 tasse', NOW(), NOW()),
(26, 'Verre', 'verre', NOW(), NOW()),
(27, 'Petit verre', 'p. verre', NOW(), NOW()),
(28, 'Grand verre', 'g. verre', NOW(), NOW()),
(29, 'Once liquide', 'fl oz', NOW(), NOW()),
(30, 'Livre anglaise', 'lbs', NOW(), NOW()),
(31, 'Pincée', 'pincée', NOW(), NOW()),
(32, 'Poignée', 'poignée', NOW(), NOW()),
(33, 'Goutte', 'gte', NOW(), NOW()),
(34, 'Trait', 'trait', NOW(), NOW()),
(35, 'Dose', 'dose', NOW(), NOW()),
(36, 'Tranche', 'tr.', NOW(), NOW()),
(37, 'Lamelle', 'lam.', NOW(), NOW()),
(38, 'Rondelle', 'rond.', NOW(), NOW()),
(39, 'Morceau', 'morc.', NOW(), NOW()),
(40, 'Petit morceau', 'p. morc.', NOW(), NOW()),
(41, 'Grand morceau', 'g. morc.', NOW(), NOW()),
(42, 'Barquette', 'barq.', NOW(), NOW()),
(43, 'Boîte', 'bte', NOW(), NOW()),
(44, 'Conserve', 'cons.', NOW(), NOW()),
(45, 'Brique', 'briq.', NOW(), NOW()),
(46, 'Sachet', 'sachet', NOW(), NOW()),
(47, 'Paquet', 'pqt', NOW(), NOW()),
(48, 'Tablette', 'tablette', NOW(), NOW()),
(49, 'Plaque', 'plq', NOW(), NOW()),
(50, 'Ramequin', 'ram.', NOW(), NOW()),
(51, 'Moule', 'mle', NOW(), NOW()),
(52, 'Bocal', 'boc.', NOW(), NOW()),
(53, 'Pot', 'pot', NOW(), NOW()),
(54, 'Bouteille', 'bouteille', NOW(), NOW()),
(55, 'Quart', '1/4', NOW(), NOW()),
(56, 'Demi', '1/2', NOW(), NOW()),
(57, 'Trois quart', '3/4', NOW(), NOW()),
(58, 'Douzaine', 'dz', NOW(), NOW()),
(59, 'Demie douzaine', '1/2 dz', NOW(), NOW());
