INSERT INTO `sub_category` (`id`, `category_id`, `label`, `sort`, `slug`, `created_at`, `updated_at`) VALUES
(1, 1, 'Assaisonnement', 1, 'assaisonnement', NOW(), NOW()),
(2, 1, 'Béchamel', 2, 'bechamel', NOW(), NOW()),
(3, 1, 'Confits', 3, 'confits', NOW(), NOW()),
(4, 1, 'Fromage', 4, 'fromage', NOW(), NOW()),
(5, 1, 'Mayonnaise', 5, 'mayonnaise', NOW(), NOW()),
(6, 1, 'Pâte à pain', 6, 'pate-a-pain', NOW(), NOW()),
(7, 1, 'Pâte à pizza', 7, 'pate-a-pizza', NOW(), NOW()),
(8, 1, 'Pâte feuilletée', 8, 'pate-feuilletee', NOW(), NOW()),
(9, 1, 'Pâte sablée', 9, 'pate-sablee', NOW(), NOW()),
(10, 1, 'Sauces', 10, 'sauces', NOW(), NOW()),
(11, 1, 'Vinaigrette', 11, 'vinaigrette', NOW(), NOW()),
(12, 3, 'Entrée froide', 1, 'entree-froide', NOW(), NOW()),
(13, 3, 'Entrée chaude', 2, 'entree-chaude', NOW(), NOW()),
(14, 3, 'Bouchée et raviolis', 3, 'bouchee-et-raviolis', NOW(), NOW()),
(15, 3, 'Feuilleté, Brick', 4, 'feuillete-brick', NOW(), NOW()),
(16, 3, 'Entrée facile', 5, 'entree-facile', NOW(), NOW()),
(17, 3, 'Entrée rapide', 6, 'entree-rapide', NOW(), NOW()),
(18, 3, 'Entrée légère', 7, 'entree-legere', NOW(), NOW()),
(19, 3, 'Entrée de Noël', 8, 'entree-de-noel', NOW(), NOW()),
(20, 4, 'Viande', 1, 'viande', NOW(), NOW()),
(21, 4, 'Volaille', 2, 'volaille', NOW(), NOW()),
(22, 4, 'Gibier', 3, 'gibier', NOW(), NOW()),
(23, 4, 'Poisson', 4, 'poisson', NOW(), NOW()),
(24, 4, 'Fruits de mer', 5, 'fruits-de-mer', NOW(), NOW()),
(25, 4, 'Plat unique', 6, 'plat-unique', NOW(), NOW()),
(26, 4, 'Oeufs', 7, 'oeufs', NOW(), NOW()),
(27, 4, 'Plat végétarien', 8, 'plat-vegetarien', NOW(), NOW()),
(28, 4, 'Pâtes, riz, semoule', 9, 'pates-riz-semoule', NOW(), NOW()),
(29, 4, 'Pizza, quiche', 10, 'pizza-quiche', NOW(), NOW()),
(30, 4, 'Plats au fromage', 11, 'plats-au-fromage', NOW(), NOW()),
(31, 5, 'Dessert au chocolat', 1, 'dessert-au-chocolat', NOW(), NOW()),
(32, 5, 'Gâteau', 2, 'gateau', NOW(), NOW()),
(33, 5, 'Flan', 3, 'flan', NOW(), NOW()),
(34, 5, 'Crème', 4, 'creme', NOW(), NOW()),
(35, 5, 'Mousse', 5, 'mousse', NOW(), NOW()),
(36, 5, 'Crumble', 6, 'crumble', NOW(), NOW()),
(37, 5, 'Beignet et friture', 7, 'beignet-et-friture', NOW(), NOW()),
(38, 5, 'Tarte', 8, 'tarte', NOW(), NOW()),
(39, 5, 'Choux', 9, 'choux', NOW(), NOW()),
(40, 5, 'Galette des rois', 10, 'galette-des-rois', NOW(), NOW()),
(41, 5, 'Bûche de Noël', 11, 'buche-de-noel', NOW(), NOW()),
(42, 5, 'Mille-feuille', 12, 'mille-feuille', NOW(), NOW()),
(43, 5, 'Cheesecake', 13, 'cheesecake', NOW(), NOW()),
(44, 5, 'Tiramisu', 14, 'tiramisu', NOW(), NOW()),
(45, 5, 'Salade de fruits', 15, 'salade-de-fruits', NOW(), NOW()),
(46, 5, 'Compote', 16, 'compote', NOW(), NOW()),
(47, 5, 'Pomme au four', 17, 'pomme-au-four', NOW(), NOW()),
(48, 5, 'Viennoiseries', 18, 'viennoiseries', NOW(), NOW()),
(49, 5, 'Brioche', 19, 'brioche', NOW(), NOW()),
(50, 5, 'Gaufre', 20, 'gaufre', NOW(), NOW()),
(51, 5, 'Crêpe', 21, 'crepe', NOW(), NOW()),
(52, 5, 'Pain perdu', 22, 'pain-perdu', NOW(), NOW()),
(53, 5, 'Pain d\'épices', 23, 'pain-d-epices', NOW(), NOW()),
(54, 5, 'Entremets', 24, 'entremets', NOW(), NOW()),
(55, 6, 'Boisson chaude', 1, 'boisson-chaude', NOW(), NOW()),
(56, 6, 'Boisson froide', 2, 'boisson-froide', NOW(), NOW()),
(57, 6, 'Cocktail alcoolisé', 3, 'cocktail-alcoolise', NOW(), NOW()),
(58, 6, 'Cocktail sans alcool', 4, 'cocktail-sans-alcool', NOW(), NOW());
